### ISSUE TITLE
Fix evaluation compile at every step

### ISSUE THREAD

**Issue by michaelbenayoun** [huggingface/optimum-neuron#216]
It seems that either compilation re-happens at every evaluation step, or that it accumulates multiple graphs.
Might be related to a missing barrier.

**Comment by samir-souza** [comment]
Hi @michaelbenayoun is something like this you're observing in the training output during evaluation?

```
023-09-11 13:36:10.000941: INFO \|\|NCC_WRAPPER\|\|: Compile cache path: /tmp/tmp1lg6qutl/neuron-compile-cache
--
2023-09-11 13:36:10.000941: INFO \|\|NCC_WRAPPER\|\|: Compile cache path: /tmp/tmp1lg6qutl/neuron-compile-cache
.
.
Non-output memory location with no reader {_convert-t151}@SB<0,0>(1x4)#Internal DebugInfo: <_convert\|\|UNDEF\|\|[1, 1, 1]>
Non-output memory location with no reader {_convert-t151}@SB<0,0>(1x4)#Internal DebugInfo: <_convert\|\|UNDEF\|\|[1, 1, 1]>
Compiler status PASS
Compiler status PASS
4%\|▍         \| 6/137 [04:59<2:00:22, 55.13s/it]#033[A
2023-09-11 13:36:17.000464: INFO \|\|NCC_WRAPPER\|\|: Compile cache path: /tmp/tmp1lg6qutl/neuron-compile-cache
.
```

This is happening with every text-classification evaluation code I'm running... If that is the case, any workaround?

**Comment by michaelbenayoun** [comment]
No I don't see that but I see compilation re-happening at every step. Will have a look once I have more bandwitdth.

**Comment by samir-souza** [comment]
It would be good to give a higher priority to this one. It makes optimum neuron useless for training medium/large models. During evaluation, all the compilation steps accumulate and at the end it takes forever for the process to finish. I ran some experiments and noticed this issue is related to transformers>4.30.0 (any version higher than 4.30.0). Something changed in version 4.31.0 that is causing this issue. Given Optimum Neuron version 0.0.11 requires transformers 4.32.0 or higher, it doesn't work.

I tested with NeuronSDK 2.12 & 2.13.2 and the results were the same for the following **requirements.txt** configurations:

WORKS
evaluate==0.4.0
accelerate==0.21.0
scikit-learn==1.3.0
optimum-neuron==**0.0.8**
transformers==**4.30.0**

WORKS
evaluate==0.4.0
accelerate==0.21.0
scikit-learn==1.3.0
optimum-neuron==**0.0.9**
transformers==**4.30.0**

WORKS
evaluate==0.4.0
accelerate==0.21.0
scikit-learn==1.3.0
optimum-neuron==**0.0.10**
transformers==**4.30.0**

DOESN'T WORK
evaluate==0.4.0
accelerate==0.21.0
scikit-learn==1.3.0
optimum-neuron==**0.0.11**
transformers==**4.32.1**

DOESN'T WORK
evaluate==0.4.0
accelerate==**0.23.0**
scikit-learn==1.3.0
git+https://github.com/huggingface/optimum-neuron.git
transformers==**4.32.1**
