### ISSUE TITLE
Optimum Neuron Bug Bash - Update doc to clear memory after SDXL compilation

### ISSUE THREAD

**Issue by brianloyal** [huggingface/optimum-neuron#430]
When following the tutorial at https://github.com/huggingface/optimum-neuron/blob/main/notebooks/stable-diffusion/stable-diffusion-xl-txt2img.ipynb I noticed that I needed to restart my kernel after the compilation step. Otherwise I would hit an OOM error durting model load. This is on a trn1.32xlarge instance running the huggingface-neuron-2023-12-20T10-12-07.416Z-692efe1a-8d5c-4033-bcbc-5d99f2d4ae6a AMI

**Comment by JingyaHuang** [comment]
Hi @brianloyal, if you follow the compilation section which compiles the model, the model will be already loaded into neuron after the compilation, so there is no need to run the first line of the inference section. 
(
```python
stable_diffusion_xl = NeuronStableDiffusionXLPipeline.from_pretrained(save_directory)
```
)  
Otherwise, the checkpoint will be loaded twice and potentially run OOM. I will add a reminder in the notebook!
